// Auth Action Types

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_START = 'SIGN_UP_START';
export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Project Action Types

export const FETCH_IDS_START = 'FETCH_IDS_START';
export const FETCH_IDS_SUCCESS = 'FETCH_IDS_SUCCESS';
export const FETCH_PROJECT_START = 'FETCH_PROJECT_START';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';
export const CREATE_PROJECT_START = 'CREATE_PROJECT_START';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const FETCH_PROJECT_BY_ID_START = 'FETCH_PROJECT_BY_ID_START';
export const FETCH_PROJECT_BY_ID_SUCCESS = 'FETCH_PROJECT_BY_ID_SUCCESS';
export const DELETE_PROJECT_START = 'DELETE_PROJECT_START';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const UPDATE_PROJECT_START = 'UPDATE_PROJECT_START';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const SET_MAP_ID_NAME_PROJECT = 'SET_MAP_ID_NAME_PROJECT';

// TASK Action Types

export const TASK_FORM_IDS_START = 'TASK_FORM_IDS_START';
export const TASK_FORM_IDS_SUCCESS = 'TASK_FORM_IDS_SUCCESS';
export const FETCH_TASK_START = 'FETCH_TASK_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASK_FAIL = 'FETCH_TASK_FAIL';
export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const FETCH_TASK_BY_ID_START = 'FETCH_TASK_BY_ID_START';
export const FETCH_TASK_BY_ID_SUCCESS = 'FETCH_TASK_BY_ID_SUCCESS';
export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_TASK_START = 'UPDATE_TASK_START';
export const UPDATE_TASK = 'UPDATE_TASK';
export const SET_MAP_ID_NAME_BACKLOG = 'SET_MAP_ID_NAME_BACKLOG';

// SPRINT Action Types

export const SPRINT_FORM_IDS_START = 'SPRINT_FORM_IDS_START';
export const SPRINT_FORM_IDS_SUCCESS = 'SPRINT_FORM_IDS_SUCCESS';
export const FETCH_SPRINT_START = 'FETCH_SPRINT_START';
export const FETCH_SPRINTS_SUCCESS = 'FETCH_SPRINTS_SUCCESS';
export const FETCH_SPRINT_FAIL = 'FETCH_SPRINT_FAIL';
export const CREATE_SPRINT_START = 'CREATE_SPRINT_START';
export const CREATE_SPRINT_SUCCESS = 'CREATE_SPRINT_SUCCESS';
export const FETCH_SPRINT_BY_ID_START = 'FETCH_SPRINT_BY_ID_START';
export const FETCH_SPRINT_BY_ID_SUCCESS = 'FETCH_SPRINT_BY_ID_SUCCESS';
export const DELETE_SPRINT_START = 'DELETE_SPRINT_START';
export const DELETE_SPRINT = 'DELETE_SPRINT';
export const UPDATE_SPRINT_START = 'UPDATE_SPRINT_START';
export const UPDATE_SPRINT = 'UPDATE_SPRINT';
export const SET_MAP_ID_NAME_SPRINT = 'SET_MAP_ID_NAME_SPRINT';

// EMPLOYEE Action Types

export const EMPLOYEE_FORM_IDS_START = 'EMPLOYEE_FORM_IDS_START';
export const EMPLOYEE_FORM_IDS_SUCCESS = 'EMPLOYEE_FORM_IDS_SUCCESS';
export const FETCH_EMPLOYEE_START = 'FETCH_EMPLOYEE_START';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEE_FAIL = 'FETCH_EMPLOYEE_FAIL';
export const CREATE_EMPLOYEE_START = 'CREATE_EMPLOYEE_START';
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_BY_ID_START = 'FETCH_EMPLOYEE_BY_ID_START';
export const FETCH_EMPLOYEE_BY_ID_SUCCESS = 'FETCH_EMPLOYEE_BY_ID_SUCCESS';
export const DELETE_EMPLOYEE_START = 'DELETE_EMPLOYEE_START';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const UPDATE_EMPLOYEE_START = 'UPDATE_EMPLOYEE_START';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const SET_MAP_ID_NAME_EMPLOYEE = 'SET_MAP_ID_NAME_EMPLOYEE';

// STATUS Action Types

export const FETCH_STATUS_START = 'FETCH_STATUS_START';
export const FETCH_STATUSES_SUCCESS = 'FETCH_STATUSES_SUCCESS';
export const FETCH_STATUS_FAIL = 'FETCH_STATUS_FAIL';
export const CREATE_STATUS_START = 'CREATE_STATUS_START';
export const CREATE_STATUS_SUCCESS = 'CREATE_STATUS_SUCCESS';
export const FETCH_STATUS_BY_ID_START = 'FETCH_STATUS_BY_ID_START';
export const FETCH_STATUS_BY_ID_SUCCESS = 'FETCH_STATUS_BY_ID_SUCCESS';
export const DELETE_STATUS_START = 'DELETE_STATUS_START';
export const DELETE_STATUS = 'DELETE_STATUS';
export const UPDATE_STATUS_START = 'UPDATE_STATUS_START';
export const UPDATE_STATUS = 'UPDATE_STATUS';

// ROLE Action Types

export const FETCH_ROLE_START = 'FETCH_ROLE_START';
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const FETCH_ROLE_FAIL = 'FETCH_ROLE_FAIL';
export const CREATE_ROLE_START = 'CREATE_ROLE_START';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const FETCH_ROLE_BY_ID_START = 'FETCH_ROLE_BY_ID_START';
export const FETCH_ROLE_BY_ID_SUCCESS = 'FETCH_ROLE_BY_ID_SUCCESS';
export const DELETE_ROLE_START = 'DELETE_ROLE_START';
export const DELETE_ROLE = 'DELETE_ROLE';
export const UPDATE_ROLE_START = 'UPDATE_ROLE_START';
export const UPDATE_ROLE = 'UPDATE_ROLE';

// PERMISSION Action Types

export const FETCH_PERMISSION_START = 'FETCH_PERMISSION_START';
export const FETCH_PERMISSIONS_SUCCESS = 'FETCH_PERMISSIONS_SUCCESS';
export const FETCH_PERMISSION_FAIL = 'FETCH_PERMISSION_FAIL';
export const CREATE_PERMISSION_START = 'CREATE_PERMISSION_START';
export const CREATE_PERMISSION_SUCCESS = 'CREATE_PERMISSION_SUCCESS';
export const FETCH_PERMISSION_BY_ID_START = 'FETCH_PERMISSION_BY_ID_START';
export const FETCH_PERMISSION_BY_ID_SUCCESS = 'FETCH_PERMISSION_BY_ID_SUCCESS';
export const DELETE_PERMISSION_START = 'DELETE_PERMISSION_START';
export const DELETE_PERMISSION = 'DELETE_PERMISSION';
export const UPDATE_PERMISSION_START = 'UPDATE_PERMISSION_START';
export const UPDATE_PERMISSION = 'UPDATE_PERMISSION';

// IMPUTATION Action Types

export const IMPUTATION_FORM_IDS_START = 'IMPUTATION_FORM_IDS_START';
export const IMPUTATION_FORM_IDS_SUCCESS = 'IMPUTATION_FORM_IDS_SUCCESS';
export const FETCH_IMPUTATION_START = 'FETCH_IMPUTATION_START';
export const FETCH_IMPUTATIONS_SUCCESS = 'FETCH_IMPUTATIONS_SUCCESS';
export const FETCH_IMPUTATION_FAIL = 'FETCH_IMPUTATION_FAIL';
export const CREATE_IMPUTATION_START = 'CREATE_IMPUTATION_START';
export const CREATE_IMPUTATION_SUCCESS = 'CREATE_IMPUTATION_SUCCESS';
export const FETCH_IMPUTATION_BY_ID_START = 'FETCH_IMPUTATION_BY_ID_START';
export const FETCH_IMPUTATION_BY_ID_SUCCESS = 'FETCH_IMPUTATION_BY_ID_SUCCESS';
export const DELETE_IMPUTATION_START = 'DELETE_IMPUTATION_START';
export const DELETE_IMPUTATION = 'DELETE_IMPUTATION';
export const UPDATE_IMPUTATION_START = 'UPDATE_IMPUTATION_START';
export const UPDATE_IMPUTATION = 'UPDATE_IMPUTATION';
export const SET_MAP_ID_NAME_IMPUTATION = 'SET_MAP_ID_NAME_IMPUTATION';
