// Auth Action Types

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_START = 'SIGN_UP_START';
export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Project Action Types

export const FETCH_IDS_START = 'FETCH_IDS_START';
export const FETCH_IDS_SUCCESS = 'FETCH_IDS_SUCCESS';
export const FETCH_PROJECT_START = 'FETCH_PROJECT_START';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';
export const CREATE_PROJECT_START = 'CREATE_PROJECT_START';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const FETCH_PROJECT_BY_ID_START = 'FETCH_PROJECT_BY_ID_START';
export const FETCH_PROJECT_BY_ID_SUCCESS = 'FETCH_PROJECT_BY_ID_SUCCESS';
export const DELETE_PROJECT_START = 'DELETE_PROJECT_START';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const UPDATE_PROJECT_START = 'UPDATE_PROJECT_START';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
